name: Publish Documentation
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install PlantUML and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml graphviz
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Retrieve version
        run: echo "WORKFLOWS_VERSION=$(hatch version)" >> "$GITHUB_ENV"
      - name: Set User
        run: |
            git config --local user.name "GitHub Actions"
            git config --local user.email "action@github.com"
      - name: Publish documentation
        run: |
          git fetch origin gh-pages --depth=1
          hatch env run -e docs -- mike deploy --update-aliases --push ${{ env.WORKFLOWS_VERSION }} latest
      - name: Update default version
        run: hatch env run -e docs -- mike set-default --push ${{ env.WORKFLOWS_VERSION }}