name: Publish Documentation
on:
  release:
    types: [published]
permissions:
    contents: write
jobs:
  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Setup environment
        run: hatch env +py=3.13 create docs
      - name: Retrieve version
        run: echo "WORKFLOWS_VERSION=$(hatch version)" >> "$GITHUB_ENV"
      - name: Publish documentation
        run: hatch env run -e docs -- mike deploy --update-aliases ${{ env.WORKFLOWS_VERSION }} latest
      - name: Update default version
        run: hatch env run -e docs -- mike set-default ${{ env.WORKFLOWS_VERSION }}