name: Release New Version
on:
  workflow_dispatch:
    inputs:
      force_update:
        type: boolean
        description: "Force update even if version exists"
        default: false
  release:
    types: [published]
env:
  REPOSITORY_NAME: workflows-manager
jobs:
  create-release:
    name: Create a new release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Setup environment
        run: hatch build
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dist
          path: dist/

  check-version-pypi:
    name: Check if version exists on PyPI
    runs-on: ubuntu-latest
    outputs:
      version_exists: ${{ steps.check_pypi.outputs.version_exists }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Hatch
        run: python3 -m pip install hatch
      - name: Get Version from Hatch
        id: get_version
        run: |
          VERSION=$(hatch version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Check PyPI for existing version
        id: check_pypi
        run: |
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/${{ env.REPOSITORY_NAME }}/${{ env.VERSION }}/json)
          echo "version_exists=$([ "$HTTP_CODE" == "200" ] && echo true || echo false)" >> $GITHUB_OUTPUT

  publish-library-dev:
    name: Publish new release on dev
    needs: ['create-release', 'check-version-pypi']
    if: needs.check-version-pypi.outputs.version_exists != 'true' || github.event.inputs.force_update == 'true'
    permissions: write-all
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: "https://test.pypi.org/project/${{ env.REPOSITORY_NAME }}/"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
          path: dist/
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"

  publish-library-prod:
    name: Publish new release on prod
    needs: ['create-release', 'publish-library-dev']
    if: needs.check-version-pypi.outputs.version_exists != 'true' || github.event.inputs.force_update == 'true'
    permissions: write-all
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: "https://pypi.org/project/${{ env.REPOSITORY_NAME }}/"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-dist
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
